version: '3'

volumes:
  portainer_data:

services:
  dgi_catalog_nginx:
    container_name: dgi_catalog_nginx
    image: nginx:1.17.6
    # restart: always
    volumes:
      - ./volumes/nginx/nginx.dev.template:/etc/nginx/conf.d/mysite.template
      # - /path/files/png:/var/www/html/datastore
    env_file:
      - ./env_files/nginx.env
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 8089:8089
    networks:
      - dgi_catalog
    depends_on:
      - dgi_catalog_api
      - dgi_catalog_inpe_stac
      - dgi_catalog_portainer
      - dgi_catalog_geoserver
      - dgi_catalog_stac_compose

  dgi_catalog_portal:
    container_name: dgi_catalog_portal
    image: dgi-catalog-frontend
    command: npm start
    # restart: always
    env_file:
      - ./env_files/portal.env
    volumes:
      - ../dgi-catalog-frontend/portal:/app
    ports:
      - "5000:8000"
    networks:
      - dgi_catalog

  dgi_catalog_api:
    container_name: dgi_catalog_api
    image: dgi-catalog-backend
    command: python3 manage.py run
    # restart: always
    volumes:
      - ../dgi-catalog-backend:/app
    env_file:
      - ./env_files/api.env
    ports:
      - "5001:5001"
    networks:
      - dgi_catalog

  dgi_catalog_inpe_stac:
    container_name: dgi_catalog_inpe_stac
    image: inpe_stac
    command: flask run --host=0.0.0.0
    # restart: always
    volumes:
      - ../inpe-stac/inpe_stac:/inpe_stac
    env_file:
      - ./env_files/inpe_stac.env
    ports:
      - "5002:5000"
    networks:
      - dgi_catalog

  dgi_catalog_stac_compose:
    container_name: dgi_catalog_stac_compose
    image: stac_compose
    command: python3 manage.py run
    # restart: always
    volumes:
      - ../stac-compose:/bdc-stac-compose
      - ./volumes/stac-compose/providers/providers.json:/bdc-stac-compose/bdc_search_stac/providers/static/providers.json
    env_file:
      - ./env_files/stac_compose.env
    ports:
      - "5003:5002"
    networks:
      - dgi_catalog

  dgi_catalog_portainer:
    container_name: dgi_catalog_portainer
    image: portainer/portainer:1.23.0
    # restart: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
    networks:
      - dgi_catalog

  dgi_catalog_geoserver:
    container_name: dgi_catalog_geoserver
    image: kartoza/geoserver:2.15.2
    # restart: always
    volumes:
      - ./volumes/geoserver/geoserverdata:/opt/geoserver/data_dir
      - ./volumes/geoserver/grids:/home/data/grids
      - ./volumes/geoserver/web.xml:/usr/local/tomcat/webapps/geoserver/WEB-INF/web.xml
    env_file:
      - ./env_files/geoserver.env
    ports:
      - 9001:8080
    networks:
      - dgi_catalog

  dgi_catalog_db:
    container_name: dgi_catalog_db
    image: mariadb:10.4.11
    restart: always
    volumes:
      - ./data/mysqldata:/var/lib/mysql
    env_file:
      - ./env/db.env
    networks:
      - dgi_catalog
    ports:
      - 3311:3306

  dgi_catalog_admin:
    container_name: dgi_catalog_admin
    image: phpmyadmin/phpmyadmin:4.9
    restart: always
    env_file:
      - ./env/phpmyadmin.env
    networks:
      - dgi_catalog
    ports:
      - 8099:80

  # dgi_catalog_publisher:
  #   container_name: dgi_catalog_publisher
  #   image: publisher
  #   restart: always
  #   user: 1648:1648
  #   volumes:
  #     - ./publisher:/app
  #     - ./publisher:/config
  #     - /data/TIFF/CBERS4:/CBERS4
  #     - /data/TIFF/LANDSAT5:/LANDSAT5
  #   env_file:
  #     - ./env/publisher.env
  #   networks:
  #     - dgi_catalog
  #   ports:
  #     - 5022:5022

networks:
  dgi_catalog:
    driver: bridge
