version: '3'

volumes:
  portainer_data:

services:
  inpe_cdsr_nginx:
    container_name: inpe_cdsr_nginx
    image: nginx:1.17.6
    # restart: always
    volumes:
      - ./volumes/nginx/nginx.dev.template:/etc/nginx/conf.d/mysite.template
      - /data/TIFF:/var/www/html/datastore/TIFF
    env_file:
      - ./env_files/nginx.env
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - inpe_cdsr
    depends_on:
      - inpe_cdsr_frontend
      - inpe_cdsr_backend
      - inpe_cdsr_inpe_stac
      - inpe_cdsr_stac_compose
      - inpe_cdsr_portainer
      - inpe_cdsr_geoserver
    ports:
      - 8089:8089

  inpe_cdsr_frontend:
    container_name: inpe_cdsr_frontend
    image: dgi-catalog-frontend
    command: npm start
    # restart: always
    env_file:
      - ./env_files/frontend.env
    volumes:
      - ../catalog-frontend/portal:/app
    networks:
      - inpe_cdsr
    ports:
      - 5000:8000

  inpe_cdsr_backend:
    container_name: inpe_cdsr_backend
    image: dgi-catalog-backend
    command: python3 manage.py run
    # restart: always
    volumes:
      - ../catalog-backend:/app
      - /data/TIFF:/TIFF
    env_file:
      - ./env_files/backend.env
    networks:
      - inpe_cdsr
    ports:
      - 5001:5001

  inpe_cdsr_inpe_stac:
    container_name: inpe_cdsr_inpe_stac
    image: inpe_stac
    command: flask run
    # restart: always
    volumes:
      - ../inpe-stac/inpe_stac:/inpe_stac
    env_file:
      - ./env_files/inpe_stac.env
    networks:
      - inpe_cdsr
    ports:
      - 5002:5000

  inpe_cdsr_stac_compose:
    container_name: inpe_cdsr_stac_compose
    image: stac_compose
    command: python3 -u manage.py run
    # restart: always
    volumes:
      - ../stac-compose:/bdc-stac-compose
      - ./volumes/stac-compose/providers/providers.json:/bdc-stac-compose/bdc_search_stac/providers/static/providers.json
    env_file:
      - ./env_files/stac_compose.env
    networks:
      - inpe_cdsr
    ports:
      - 5003:5002

  inpe_cdsr_portainer:
    container_name: inpe_cdsr_portainer
    image: portainer/portainer:1.23.0
    # restart: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - inpe_cdsr
    ports:
      - 9000:9000

  inpe_cdsr_geoserver:
    container_name: inpe_cdsr_geoserver
    image: kartoza/geoserver:2.15.2
    # restart: always
    volumes:
      - ./volumes/geoserver/geoserverdata:/opt/geoserver/data_dir
      - ./volumes/geoserver/grids:/home/data/grids
      - ./volumes/geoserver/web.xml:/usr/local/tomcat/webapps/geoserver/WEB-INF/web.xml
    env_file:
      - ./env_files/geoserver.env
    networks:
      - inpe_cdsr
    ports:
      - 9001:8080

  inpe_cdsr_db:
    container_name: inpe_cdsr_db
    image: mariadb:10.4.11
    # restart: always
    volumes:
      - ../data/mysqldata:/var/lib/mysql
    env_file:
      - ./env_files/db.env
    networks:
      - inpe_cdsr
    ports:
      - 3311:3306

  inpe_cdsr_phpmyadmin:
    container_name: inpe_cdsr_phpmyadmin
    image: phpmyadmin/phpmyadmin:4.9
    # restart: always
    env_file:
      - ./env_files/phpmyadmin.env
    networks:
      - inpe_cdsr
    ports:
      - 8099:80

networks:
  inpe_cdsr:
    driver: bridge
