
version: '3'

volumes:
  portainer_data:

services:
  inpe_cdsr_nginx:
    container_name: inpe_cdsr_nginx
    image: nginx:1.17.6
    restart: always
    volumes:
      - ./volumes/nginx/nginx.template:/etc/nginx/conf.d/mysite.template
      - ./volumes/nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./volumes/nginx/include:/etc/nginx/conf.d/include
      - ${DATA_TIFF}:/var/www/html/datastore/TIFF
    env_file:
      - ./env_files/nginx.env
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - inpe_cdsr
    depends_on:
      - inpe_cdsr_catalog_frontend
      - inpe_cdsr_catalog_dash
      - inpe_cdsr_stac_compose
      - inpe_cdsr_portainer
      - inpe_cdsr_geoserver
      - inpe_cdsr_phpmyadmin
    ports:
      - 8089:8089

  inpe_cdsr_catalog_frontend:
    container_name: inpe_cdsr_catalog_frontend
    image: registry.dpi.inpe.br/inpe-cdsr/catalog-frontend:0.0.19
    restart: always
    env_file:
      - ./env_files/frontend.env
    networks:
      - inpe_cdsr
    # ports:
    #   - 8002:8000

  inpe_cdsr_catalog_backend:
    container_name: inpe_cdsr_catalog_backend
    image: registry.dpi.inpe.br/inpe-cdsr/catalog-backend:0.0.10
    restart: always
    volumes:
      - ${DATA_TIFF}:/TIFF
    env_file:
      - ./env_files/backend.env
    networks:
      - inpe_cdsr
    # ports:
    #   - 5022:5000

  inpe_cdsr_catalog_dash:
    container_name: inpe_cdsr_catalog_dash
    image: registry.dpi.inpe.br/inpe-cdsr/catalog-dash:0.0.10
    restart: always
    env_file:
      - ./env_files/catalog_dash.env
    networks:
      - inpe_cdsr
    depends_on:
      - inpe_cdsr_db
    # ports:
    #   - 5003:8050

  inpe_cdsr_inpe_stac:
    container_name: inpe_cdsr_inpe_stac
    image: registry.dpi.inpe.br/inpe-cdsr/inpe-stac:0.0.13
    restart: always
    env_file:
      - ./env_files/inpe_stac.env
    networks:
      - inpe_cdsr
    # ports:
    #  - 5002:5000

  inpe_cdsr_stac_compose:
    container_name: inpe_cdsr_stac_compose
    image: registry.dpi.inpe.br/inpe-cdsr/stac-compose:0.0.6
    restart: always
    env_file:
      - ./env_files/stac_compose.env
    volumes:
      - ./volumes/stac-compose/providers/providers.json:/app/stac_compose/providers/static/providers.json
    networks:
      - inpe_cdsr
    # ports:
    #   - 5001:8002

  inpe_cdsr_portainer:
    container_name: inpe_cdsr_portainer
    image: portainer/portainer:1.23.0
    restart: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - inpe_cdsr
    # ports:
    #   - 9000:9000

  inpe_cdsr_geoserver:
    container_name: inpe_cdsr_geoserver
    image: kartoza/geoserver:2.15.2
    restart: always
    volumes:
      - ./volumes/geoserver/geoserverdata:/opt/geoserver/data_dir
      - ./volumes/geoserver/grids:/home/data/grids
      - ./volumes/geoserver/web.xml:/usr/local/tomcat/webapps/geoserver/WEB-INF/web.xml
    env_file:
      - ./env_files/geoserver.env
    networks:
      - inpe_cdsr
    # ports:
    #   - 9003:8080

  inpe_cdsr_db:
    container_name: inpe_cdsr_db
    image: mariadb:10.5.3
    restart: always
    volumes:
      - ../data/mysqldata:/var/lib/mysql
      - ./volumes/mysql/config-file.cnf:/etc/mysql/conf.d/config-file.cnf
    env_file:
      - ./env_files/db.env
    networks:
      - inpe_cdsr
    ports:
      - 9004:3306

  inpe_cdsr_phpmyadmin:
    container_name: inpe_cdsr_phpmyadmin
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    env_file:
      - ./env_files/phpmyadmin.env
    volumes:
      - ./volumes/phpmyadmin/php.ini:/usr/local/etc/php/php.ini
    networks:
      - inpe_cdsr
    ports:
      - 8099:80

networks:
  inpe_cdsr:
    driver: bridge
