version: '3'

volumes:
  portainer_data:

services:
  dgi_catalog_nginx:
    container_name: dgi_catalog_nginx
    image: nginx:1.17.6
    # restart: always
    volumes:
      - ./volumes/nginx/nginx.dev.template:/etc/nginx/conf.d/mysite.template
      - /data/TIFF/:/var/www/html/datastore
    env_file:
      - ./env_files/nginx.env
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - dgi_catalog
    depends_on:
      - dgi_catalog_frontend
      - dgi_catalog_backend
      - dgi_catalog_inpe_stac
      - dgi_catalog_stac_compose
      - dgi_catalog_portainer
      - dgi_catalog_geoserver
    ports:
      - 8089:8089

  dgi_catalog_frontend:
    container_name: dgi_catalog_frontend
    image: dgi-catalog-frontend
    command: npm start
    # restart: always
    env_file:
      - ./env_files/frontend.env
    volumes:
      - ../catalog-frontend/portal:/app
    networks:
      - dgi_catalog
    ports:
      - 5000:8000

  dgi_catalog_backend:
    container_name: dgi_catalog_backend
    image: dgi-catalog-backend
    command: python3 manage.py run
    # restart: always
    volumes:
      - ../catalog-backend:/app
      - /data/TIFF/CBERS4:/CBERS4
      - /data/TIFF/CBERS4A:/CBERS4A
      - /data/TIFF/LANDSAT5:/LANDSAT5
    env_file:
      - ./env_files/backend.env
    networks:
      - dgi_catalog
    ports:
      - 5001:5001

  dgi_catalog_inpe_stac:
    container_name: dgi_catalog_inpe_stac
    image: inpe_stac
    command: flask run --host=0.0.0.0
    # restart: always
    volumes:
      - ../inpe-stac/inpe_stac:/inpe_stac
    env_file:
      - ./env_files/inpe_stac.env
    networks:
      - dgi_catalog
    ports:
      - 5002:5000

  dgi_catalog_stac_compose:
    container_name: dgi_catalog_stac_compose
    image: stac_compose
    command: python3 manage.py run
    # restart: always
    volumes:
      - ../stac-compose:/bdc-stac-compose
      - ./volumes/stac-compose/providers/providers.json:/bdc-stac-compose/bdc_search_stac/providers/static/providers.json
    env_file:
      - ./env_files/stac_compose.env
    networks:
      - dgi_catalog
    ports:
      - 5003:5002

  dgi_catalog_portainer:
    container_name: dgi_catalog_portainer
    image: portainer/portainer:1.23.0
    restart: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dgi_catalog
    ports:
      - 9000:9000

  dgi_catalog_geoserver:
    container_name: dgi_catalog_geoserver
    image: kartoza/geoserver:2.15.2
    restart: always
    volumes:
      - ./volumes/geoserver/geoserverdata:/opt/geoserver/data_dir
      - ./volumes/geoserver/grids:/home/data/grids
      - ./volumes/geoserver/web.xml:/usr/local/tomcat/webapps/geoserver/WEB-INF/web.xml
    env_file:
      - ./env_files/geoserver.env
    networks:
      - dgi_catalog
    ports:
      - 9001:8080

  dgi_catalog_db:
    container_name: dgi_catalog_db
    image: mariadb:10.4.11
    restart: always
    volumes:
      - ../data/mysqldata:/var/lib/mysql
    env_file:
      - ./env_files/db.env
    networks:
      - dgi_catalog
    ports:
      - 3311:3306

  dgi_catalog_phpmyadmin:
    container_name: dgi_catalog_phpmyadmin
    image: phpmyadmin/phpmyadmin:4.9
    restart: always
    env_file:
      - ./env_files/phpmyadmin.env
    networks:
      - dgi_catalog
    ports:
      - 8099:80

  # dgi_catalog_publisher:
  #   container_name: dgi_catalog_publisher
  #   image: publisher
  #   restart: always
  #   user: 1648:1648
  #   volumes:
  #     - ../publisher:/app
  #     - ../publisher:/config
  #     - /data/TIFF/CBERS4:/CBERS4
  #     - /data/TIFF/LANDSAT5:/LANDSAT5
  #   env_file:
  #     - ./env_files/publisher.env
  #   networks:
  #     - dgi_catalog
  #   ports:
  #     - 5022:5022

networks:
  dgi_catalog:
    driver: bridge
