version: '3'

# Source: https://github.com/kartoza/docker-geoserver

volumes:
  pg_data:
  geoserver-data:
  #  db-backups:
  portainer_data:

services:
   db:
    hostname: postgis
    container_name: postgis
    image: kartoza/postgis:12.0
    volumes:
      - pg_data:/var/lib/postgresql
    ports:
      - "9000:5432"
    env_file:
      - docker-env/db.env
    restart: on-failure
    healthcheck:
      test: "exit 0"

   geoserver:
    image: kartoza/geoserver:2.15.0
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
    ports:
      - "9001:8080"
    restart: on-failure
    env_file:
      - docker-env/geoserver.env
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

    # URL: http://localhost:8600/geoserver/web/


  #  db-dbbackups:
  #    image: kartoza/pg-backup:11.0
  #    volumes:
  #    - db-backups:/backups
  #    env_file:
  #    - docker-env/db-backups.env
  #    restart: on-failure
  #    depends_on:
  #      db:
  #        condition: service_healthy

  portainer:
    hostname: portainer
    conatiner_name: portainer
    image: portainer/portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9010:9000"
