version: '3'

# Source:
# - https://github.com/kartoza/docker-geoserver

volumes:
  portainer_data:

services:
  nginx:
    image: nginx
    container_name: dgi_catalog_nginx
    volumes:
      - ./nginx/nginx.template:/etc/nginx/conf.d/mysite.template
    env_file:
      - ./env/nginx.env
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    ports:
      - 8089:8089
    networks:
      - dgi_catalog

  portal:
    image: registry.dpi.inpe.br/dgi/catalog_app:0.0.3
    container_name: dgi_catalog_portal
    restart: always
    # ports:
    #   - "8002:8080"
    networks:
      - dgi_catalog

  api:
    image: registry.dpi.inpe.br/dgi/catalog_api:0.0.1
    container_name: dgi_catalog_api
    env_file:
      - ./env/api.env
    restart: always
    # ports:
    #   - "5022:5000"
    networks:
      - dgi_catalog

  inpe_stac:
    image: registry.dpi.inpe.br/dgi/inpe_stac:0.0.2
    container_name: dgi_catalog_inpe_stac
    env_file:
      - ./env/inpe_stac.env
    restart: always
    #ports:
    #  - 5002:5000
    networks:
      - dgi_catalog

  stac_compose:
    image: registry.dpi.inpe.br/brazildatacube/stac_compose:0.0.5
    container_name: dgi_catalog_stac_compose
    env_file:
      - ./env/stac_compose.env
    restart: always
    # ports:
    #   - "5001:8002"
    networks:
      - dgi_catalog

  portainer:
    container_name: dgi_catalog_portainer
    image: portainer/portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    # ports:
    #   - 9000:9000
    networks:
      - dgi_catalog

  geoserver:
    container_name: dgi_catalog_geoserver
    image: kartoza/geoserver:2.15.0
    volumes:
      - ./geoserver/geoserverdata:/opt/geoserver/data_dir
      - ./geoserver/grids:/home/data/grids
    env_file:
      - ./env/geoserver.env
    # ports:
    #   - 9003:8080
    restart: always
    networks:
      - dgi_catalog

networks: 
  dgi_catalog:
    driver: bridge
