version: '3'

volumes:
  portainer_data:

services:
  dgi_catalog_nginx:
    image: nginx
    container_name: dgi_catalog_nginx
    restart: always
    volumes:
      - ./nginx/nginx.template:/etc/nginx/conf.d/mysite.template
      - /path/files/png:/var/www/html/datastore
    env_file:
      - ./env/nginx.env
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 8089:8089
    networks:
      - dgi_catalog
    depends_on: 
      - dgi_catalog_api
      - dgi_catalog_inpe_stac
      - dgi_catalog_portainer
      - dgi_catalog_geoserver
      - dgi_catalog_stac_compose

  dgi_catalog_portal:
    image: registry.dpi.inpe.br/dgi/catalog_app:0.0.8
    container_name: dgi_catalog_portal
    restart: always
    env_file:
      - ./env/portal.env
    # ports:
    #   - "8002:8000"
    networks:
      - dgi_catalog

  dgi_catalog_api:
    image: registry.dpi.inpe.br/dgi/catalog_api:0.0.3
    container_name: dgi_catalog_api
    restart: always
    env_file:
      - ./env/api.env
    # ports:
    #   - "5022:5000"
    networks:
      - dgi_catalog

  dgi_catalog_inpe_stac:
    image: registry.dpi.inpe.br/dgi/inpe_stac:0.0.3
    container_name: dgi_catalog_inpe_stac
    restart: always
    env_file:
      - ./env/inpe_stac.env
    # ports:
    #  - 5002:5000
    networks:
      - dgi_catalog

  dgi_catalog_stac_compose:
    image: registry.dpi.inpe.br/dgi/stac_compose:0.0.8
    container_name: dgi_catalog_stac_compose
    restart: always
    env_file:
      - ./env/stac_compose.env
    volumes:
      - ./stac-compose/providers/providers.json:/bdc-stac-compose/bdc_search_stac/providers/static/providers.json
    # ports:
    #   - "5001:8002"
    networks:
      - dgi_catalog

  dgi_catalog_portainer:
    container_name: dgi_catalog_portainer
    image: portainer/portainer
    restart: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    # ports:
    #   - 9000:9000
    networks:
      - dgi_catalog

  dgi_catalog_geoserver:
    container_name: dgi_catalog_geoserver
    image: kartoza/geoserver:2.15.2
    restart: always
    volumes:
      - ./geoserver/geoserverdata:/opt/geoserver/data_dir
      - ./geoserver/grids:/home/data/grids
      - ./geoserver/web.xml:/usr/local/tomcat/webapps/geoserver/WEB-INF/web.xml
    env_file:
      - ./env/geoserver.env
    # ports:
    #   - 9003:8080
    networks:
      - dgi_catalog

networks: 
  dgi_catalog:
    driver: bridge
